apiVersion: v1
kind: Service
metadata:
  name: fluentd-service
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # "helm.sh/hook": "pre-install"
spec:
  ports:
  - port: 24224
    name: http-in
    targetPort: http-in
    # nodePort: 32224
    protocol: TCP
  - port: 5140
    name: fluentd
    targetPort: fluentd
    # nodePort: 32224
    protocol: TCP
  selector:
    app: fluentd
