apiVersion: v1
kind: Service
metadata:
  labels:
    tier: ingress
  name: ingress-service
  namespace: kube-system
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  - port: 443
    name: https
    protocol: TCP
    targetPort: 443
  selector:
    tier: ingress
